/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_research_jvm_nativeMethod_NativeMethodTest */

#ifndef _Included_dev_research_jvm_nativeMethod_NativeMethodTest
#define _Included_dev_research_jvm_nativeMethod_NativeMethodTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_research_jvm_nativeMethod_NativeMethodTest
 * Method:    say
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_research_jvm_nativeMethod_NativeMethodTest_say
  (JNIEnv *, jclass);

/*
 * Class:     dev_research_jvm_nativeMethod_NativeMethodTest
 * Method:    call
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dev_research_jvm_nativeMethod_NativeMethodTest_call__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_research_jvm_nativeMethod_NativeMethodTest
 * Method:    call
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_research_jvm_nativeMethod_NativeMethodTest_call__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
